namespace Unilyze;

internal static class DefaultExcludes
{
    public static readonly string[] DirectoryNames =
    [
        "Library",
        "Temp",
        "obj",
        "bin",
        ".git",
        "Logs",
        "UserSettings"
    ];

    public static readonly string[] AnyDepthDirectoryNames = ["obj", "bin", ".git"];

    public static IReadOnlyList<string> ResolveProjectPaths(string projectRoot)
        => DirectoryNames
            .Select(name => Path.GetFullPath(Path.Combine(projectRoot, name)))
            .ToList();

    public static bool IsUnderExcludedDirectory(string filePath, IReadOnlyList<string> excludeDirectories)
    {
        if (excludeDirectories.Count == 0)
            return false;

        var fullPath = Path.GetFullPath(filePath);
        foreach (var dir in excludeDirectories)
        {
            var normalizedDir = dir.EndsWith(Path.DirectorySeparatorChar)
                ? dir
                : dir + Path.DirectorySeparatorChar;
            if (fullPath.StartsWith(normalizedDir, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    public static bool ShouldExcludeSourceFile(
        string filePath,
        IReadOnlyList<string>? excludeDirectories,
        bool excludeGeneratedCode,
        string? enumerationRoot = null,
        bool applyAnyDepthExcludes = false)
    {
        if (excludeDirectories is { Count: > 0 } && IsUnderExcludedDirectory(filePath, excludeDirectories))
            return true;

        if (applyAnyDepthExcludes
            && enumerationRoot is not null
            && IsUnderAnyDepthExcludedDirectory(filePath, enumerationRoot))
            return true;

        return excludeGeneratedCode && IsGeneratedSourceFile(filePath);
    }

    public static bool IsUnderAnyDepthExcludedDirectory(string filePath, string enumerationRoot)
    {
        var relativePath = Path.GetRelativePath(
            Path.GetFullPath(enumerationRoot),
            Path.GetFullPath(filePath));

        foreach (var segment in relativePath.Split(
                     Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar))
        {
            if (AnyDepthDirectoryNames.Contains(segment, StringComparer.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    public static bool IsGeneratedSourceFile(string filePath)
    {
        if (filePath.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || filePath.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase))
            return true;

        try
        {
            using var reader = new StreamReader(filePath);
            for (var i = 0; i < 10 && !reader.EndOfStream; i++)
            {
                var line = reader.ReadLine();
                if (line is not null
                    && line.Contains("<auto-generated>", StringComparison.OrdinalIgnoreCase))
                    return true;
            }
        }
        catch (IOException)
        {
            return false;
        }

        return false;
    }

    public static bool IsStrictSubdirectory(string candidateDir, string parentDir)
    {
        var normalizedParent = parentDir.EndsWith(Path.DirectorySeparatorChar)
            ? parentDir
            : parentDir + Path.DirectorySeparatorChar;
        var normalizedCandidate = Path.GetFullPath(candidateDir);
        return normalizedCandidate.StartsWith(normalizedParent, StringComparison.OrdinalIgnoreCase)
            && !normalizedCandidate.Equals(parentDir.TrimEnd(Path.DirectorySeparatorChar), StringComparison.OrdinalIgnoreCase);
    }
}
